nk_document_file:
    resource: "routing/file.yml"
    prefix:   /files

nk_document_search:
    resource: "routing/search.yml"
    prefix:   /search

nk_document_admin:
    resource: "routing/admin.yml"
    prefix:   /documents/admin

nk_document_document:
    resource: "routing/document.yml"
    prefix:   /documents

nk_document_api:
    resource: "routing/api.yml"
    prefix:   /documents/api

