parameters:
    nk.search.limitPerPage: 25

services:
    nk.metadata_finder:
        class: nk\DocumentBundle\Services\MetadataFinder
        arguments: [@doctrine.orm.entity_manager]

    nk.zip_factory:
        class: nk\DocumentBundle\Services\ZipFactory

    nk.search_engine:
        class: nk\DocumentBundle\Services\SearchEngine
        arguments:
            - @doctrine.orm.entity_manager
            - @nk.metadata_finder
            - @knp_paginator
            - @request
            - %nk.search.limitPerPage%
        public: true
        scope: request

    nk.twig.metadata_extension:
        class: nk\DocumentBundle\Twig\MetadataExtension
        arguments:
            - @nk.metadata_finder
        tags:
            - { name: twig.extension }
