nk_document_preview:
    pattern:  /{id}/preview-document
    defaults: { _controller: nkDocumentBundle:Api:preview }
    requirements:
        id: \d+

nk_document_file_rename:
    pattern:  /{id}/rename-file
    defaults: { _controller: nkDocumentBundle:Api:rename }
    requirements:
        id: \d+

nk_document_file_remove:
    pattern:  /{id}/remove-file
    defaults: { _controller: nkDocumentBundle:Api:remove }
    requirements:
        id: \d+

nk_document_folders_for_document:
    pattern:  /{id}/folders-for-documents
    defaults: { _controller: nkDocumentBundle:Api:folders }
    requirements:
        id: \d+