nk_document_file:
    pattern:  /{id}
    defaults: { _controller: nkDocumentBundle:File:show }
    requirements:
        id: \d+

nk_document_file_download:
    pattern:  /{id}/download
    defaults: { _controller: nkDocumentBundle:File:download }
    requirements:
        id: \d+

nk_document_file_preview_slug:
    pattern:  /{slug}
    defaults: { _controller: nkDocumentBundle:File:download, inline = 1 }
    requirements:
        id: \d+
