nk_document_file:
    pattern:  /{id}
    defaults: { _controller: nkDocumentBundle:File:show }
    requirements:
        id: \d+

nk_document_file_rename:
    pattern:  /{id}/rename
    defaults: { _controller: nkDocumentBundle:File:rename }
    requirements:
        id: \d+

nk_document_file_download:
    pattern:  /{id}/download
    defaults: { _controller: nkDocumentBundle:File:download }
    requirements:
        id: \d+