nk_folder_new:
    pattern: /new
    defaults: { _controller: nkFolderBundle:Api:new }

nk_folder_rename:
    pattern: /{id}/rename
    defaults: { _controller: nkFolderBundle:Api:rename }
    requirements:
        id: \d+

nk_folder_download:
    pattern: /{id}/download
    defaults: { _controller: nkFolderBundle:Api:download }
    requirements:
        id: \d+

nk_folder_add:
    pattern: /{id}/add/{docId}
    defaults: { _controller: nkFolderBundle:Api:add }
    requirements:
        id: \d+
        docId: \d+

nk_folder_add_to_collection:
    pattern: /{id}/add-to-collection
    defaults: { _controller: nkFolderBundle:Api:addToCollection }
    requirements:
        id: \d+

nk_folder_remove_from_collection:
    pattern: /{id}/remove-from-collection
    defaults: { _controller: nkFolderBundle:Api:removeFromCollection }
    requirements:
        id: \d+

nk_folder_remove:
    pattern: /{id}/remove
    defaults: { _controller: nkFolderBundle:Api:remove }
    requirements:
        id: \d+

nk_folder_copy:
    pattern: /{id}/copy
    defaults: { _controller: nkFolderBundle:Api:copy }
    requirements:
        id: \d+