nk_api_oauth_social:
    pattern: /oauth/v2/token/google
    defaults: { _controller: nkApiBundle:Token:getSocialToken, _format: json, network: google }
    methods:  [POST]
    # requirements:
    #     network:  google
