parameters:
#    nk_folder.example.class: nk\FolderBundle\Example

services:
#    nk_folder.example:
#        class: %nk_folder.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
