nk_exam_admin:
    pattern:  /admin
    defaults: { _controller: nkExamBundle:Resource:admin }

nk_exam_admin_new:
    pattern:  /admin/new
    defaults: { _controller: nkExamBundle:Resource:new }

nk_exam_admin_edit:
    pattern:  /admin/{id}/edit
    defaults: { _controller: nkExamBundle:Resource:edit }
    requirements:
        id: \d+
