parameters:
    nk_exam.ade_url: https://planif.esiee.fr:8443/jsp/custom/modules/plannings/anonymous_cal.jsp?resources={{resources}}&projectId=3&calType=ical&nbWeeks=4

services:
#    nk_exam.example:
#        class: %nk_exam.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
