nk_user_show:
    pattern:  /{id}
    defaults: { _controller: nkUserBundle:User:show }
    requirements:
        id: \d+

nk_user_my_docs:
    pattern:  /my-documents
    defaults: { _controller: nkUserBundle:User:myDocuments }