parameters:
#    nk_user.example.class: nk\UserBundle\Example

services:
    nk_user.profile.form.type:
        class: nk\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nk_user_profile }

    nk_user.registration.form.type:
        class: nk\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nk_user_registration }
