nk_exam_next_exam:
    pattern:  /next
    defaults: { _controller: nkExamBundle:Exam:next }

nk_exam_update_database:
    pattern:  /update-database
    defaults: { _controller: nkExamBundle:Exam:update }